-- Revoke Supabase Data API table access and enable deny-by-default RLS.
-- Application table access remains available through Prisma and service_role.

REVOKE ALL PRIVILEGES ON TABLE public._prisma_migrations FROM anon, authenticated;
ALTER TABLE public._prisma_migrations ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public.addresses FROM anon, authenticated;
ALTER TABLE public.addresses ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public.balance_records FROM anon, authenticated;
ALTER TABLE public.balance_records ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public.banners FROM anon, authenticated;
ALTER TABLE public.banners ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public.carts FROM anon, authenticated;
ALTER TABLE public.carts ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public.categories FROM anon, authenticated;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public.dividends FROM anon, authenticated;
ALTER TABLE public.dividends ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public.level_snapshots FROM anon, authenticated;
ALTER TABLE public.level_snapshots ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public.manual_rewards FROM anon, authenticated;
ALTER TABLE public.manual_rewards ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public.notification_batches FROM anon, authenticated;
ALTER TABLE public.notification_batches ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public.notification_templates FROM anon, authenticated;
ALTER TABLE public.notification_templates ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public.notifications FROM anon, authenticated;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public.operation_logs FROM anon, authenticated;
ALTER TABLE public.operation_logs ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public.order_items FROM anon, authenticated;
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public.orders FROM anon, authenticated;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public.points_records FROM anon, authenticated;
ALTER TABLE public.points_records ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public.points_unlock_schedules FROM anon, authenticated;
ALTER TABLE public.points_unlock_schedules ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public.products FROM anon, authenticated;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public.recharge_audit_logs FROM anon, authenticated;
ALTER TABLE public.recharge_audit_logs ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public.recharge_reject_templates FROM anon, authenticated;
ALTER TABLE public.recharge_reject_templates ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public.recharge_requests FROM anon, authenticated;
ALTER TABLE public.recharge_requests ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public.refund_requests FROM anon, authenticated;
ALTER TABLE public.refund_requests ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public.rewards FROM anon, authenticated;
ALTER TABLE public.rewards ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public.system_configs FROM anon, authenticated;
ALTER TABLE public.system_configs ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public.users FROM anon, authenticated;
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public.withdrawal_audit_logs FROM anon, authenticated;
ALTER TABLE public.withdrawal_audit_logs ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public.withdrawal_reject_templates FROM anon, authenticated;
ALTER TABLE public.withdrawal_reject_templates ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public.withdrawals FROM anon, authenticated;
ALTER TABLE public.withdrawals ENABLE ROW LEVEL SECURITY;

REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public FROM anon, authenticated;
